require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'test' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-geolocation-service', :path => '../node_modules/react-native-geolocation-service'


  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'testTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end