
import React from 'react';
import {
  Pressable,
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
  Dimensions,
  TouchableOpacity,
  Image,
  Appearance
} from 'react-native';
const {width,height} = Dimensions.get("screen")

const them =  true//Appearance.getColorScheme() === "light";
console.log("theme:",them)

const styles = StyleSheet.create({
    isLightMode:them,
    container:{
      height,
      width,
      justifyContent:"flex-start",
      alignItems:"center",
      flexDirection:"column",
      backgroundColor:them?'#f0f1ff':'black'
    },
   subtitle1:{
   fontSize:12,
   fontWeight:"bold",
   color:"black"
  },
  subtitle:{
    color:them?"black":"white",
   fontSize:12
  },
  subtitle_gray:{
    color:them?"#8B8B8B":"white",
   fontSize:12
  },
   h1:{
     color:them?"black":"white",
     fontSize:26,
     fontWeight:"bold"
    },
   h5:{
     color:them?"#000":"white",
     fontSize:16,
     fontWeight:"bold"},
     tabtitle:{
       fontSize:10,
       color:them?"#000000":"#ccc"
     },
     tabs:{
       flexDirection:"column",
       justifyContent:"center",
       alignItems:"center",
       flex:1
     },
     tabActive:{
       color:"#C19200"
      },
       tabInactive:{
       color:"#BAC3CE"
     },
     subSection:
          { flex:1,
            marginLeft:2,
            alignItems:"flex-start",
            backgroundColor:"#FFF",
            padding:15,
            borderRadius:4,
            height:95,
            borderWidth:0.5,
            borderColor:"#C4C4C4"
          },
          ripple:{color:"rgba(255,120,9,1)"},
          cardTopRadius:{
            borderTopLeftRadius:20,
            borderTopRightRadius:20,
            backgroundColor:"white",
            overflow:"hidden"
          },
          inputWrp:{
            borderRadius:15,
            borderColor:"#9F9F9F",
            borderWidth:0.5,
            backgroundColor:"white",
            width:"100%",
            height:48,
            marginVertical:10,
            justifyContent:"center",
            alignItems:"center"
          },
          searchWrp:{
            borderRadius:4,
            backgroundColor:"rgba(159, 159, 159, 0.1)",
            width:"100%",
            height:38,
            marginVertical:10,
            justifyContent:"center",
            alignItems:"center"
          },
          smallAvatar:{
            width:51,
            height:51,
            borderRadius:51,
            backgroundColor:"#ccc",
            overflow:"hidden"
          },
          input:{
            width:"90%",
            padding:5,
            fontSize:14
          },
          floatText:{
            position:"absolute",
            left:20,
            color:"#999"
          },
          btn:{
            width:"100%",
            backgroundColor:"#001030",
            justifyContent:"center",
            alignItems:"center",
            height:48,
            borderRadius:15,
            marginVertical:10
          },
          btntxt:{
            color:"white",
            fontSize:14
          },
          greenbtn:
          {
            padding:15,
            marginTop:100,
            backgroundColor:"#669C4D",
            width:"80%",
            justifyContent:"center",
            alignItems:"center",
            borderRadius:4
          }
  });
  export default styles;